apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surrealdb-pvc
  namespace: surrealdb
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
